---
# Deploy an AWS instance
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: rfolco-key
    aws_region: us-east-1
    ami_id: ami-26ebbc5c
    instance_type: t2.micro

  tasks:
  - name: Create my own security group
    ec2_group:
      name: my_security_group
      description: "My Security Group"
      region: "{{ aws_region }}"
      rules:
        - proto: all
          cidr_ip: 0.0.0.0/0
        - proto: all
          group_name: my_security_group
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: my_security_group

  - name: Create an EC2 instance
    ec2:
      key_name: "{{ key_name }}"
      region: "{{ aws_region }}"
      group_id: "{{ my_security_group.group_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami_id }}"
      wait: yes
      volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: 80
          delete_on_termination: true
    register: ec2

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
